use_frameworks!

target 'ZXPopPresentation_Example' do
  pod 'ZXPopPresentation', :path => '../'

  target 'ZXPopPresentation_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  end
end
